### ISSUE TITLE
Welcome feedback, suggestions and requirements

### ISSUE THREAD

**Issue by ukalpa** [ukalpa/inputpicker#1]
Welcome feedback, suggestions and requirements.

**Comment by Patricia-Duarte** [comment]
Hello, I'm trying to use this plugin, but I encountered two problems, can you help me?

1º The plugin displays an error when you click an element after filtering through the written text. This error can be seen in the example "Filter input" at http://www.inputpicker.com/www/.

![cap3](https://user-images.githubusercontent.com/30505392/28682901-06dd00fe-72d5-11e7-83f6-5b18fb880fe0.PNG)

2º 
I need to reload the input at some point in my code, but after I've called the inputpicker () the first time I can not call it again, the error "is not a function" appears. Would there be any way to reload the inputpicker?

Thank you very much in advance.

**Comment by ukalpa** [comment]
Hi Patricia-Duarte,
Thank you very much for your feedback, I have revised the script and fixed these two issues. Could you please replace your local jquery.inputpicker.js as the latest version and check it?

**Comment by Patricia-Duarte** [comment]
Now it works fine. Thank's!

**Comment by dboggus** [comment]
I have a table that where the user can select a row from then click an edit button which will populate a modal window with the current values and I need to be able to set the value of a inputpicker dropdown using javascript. Is there a mechanism for doing this?

**Comment by dboggus** [comment]
I have it figured out. I am using `$('#id').inputpicker('val', 'value'); `where 'value' is the value I want to set. Problem with this is that after doing that the dropdown list is then filtered to that value and doesn't show the rest of my options so I need to understand how to clear the filter after setting the value.

**Comment by ukalpa** [comment]
Hi @dboggus ,
You can set the option "filterOpen" as false to close the filter feature, and you can refer the page to check all options it has now: http://www.inputpicker.com/www/doc.php

**Comment by Patricia-Duarte** [comment]
Hello, I found a new problem in this plugin, can you help me?

I am using the code below to load the inputpicker.

 $('#AutoCompleteCarteira').inputpicker({
            data: dados,
            fields: [
            { name: 'value', text: colunas[0] },
            { name: 'segColuna', text: colunas[1] },
            { name: 'terColuna', text: colunas[2] }
            ],
            filterOpen: true,
            filterOpen: true,
            autoOpen: true,
            headShow: true,
            fieldText: 'segColuna',
            fieldValue: 'value'
        });

The problem is that when I click on an option to select it the value of the inputpicker is the same as the fieldValue of the selected option, which is right for me, however, if I select the option by pressing the "Enter" key the value of the inputpicker is the same as the fieldValue fieldText, which is wrong for me.

How do I correct this so that the value of the inputpicker always stays the same as the fieldValue of the selected option?

**Comment by ukalpa** [comment]
Hi Patricia,
I tested your code but can not repeat the issue you described. Can you give me more details about it, the following code is the test I did on my machine:

```html

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<input id="test">
            <div id="res"></div>
		</div>
	</div>
</div>

<script>
    var i = 0;
	$(function () {
        $('#test').inputpicker({
            data: [{value:"test1", segColuna:"segColuna1", terColuna:"terColuna1" },
                {value:"test2", segColuna:"segColuna2", terColuna:"terColuna2" },
                {value:"test3", segColuna:"segColuna3", terColuna:"terColuna3" }],
            fields: [
                { name: 'value', text: "value" },
                { name: 'segColuna', text: "segColuna" },
                { name: 'terColuna', text: "terColuna" }
            ],
            filterOpen: true,
            filterOpen: true,
            autoOpen: true,
            headShow: true,
            fieldText: 'segColuna',
            fieldValue: 'value'
        });

        $('#test').change(function(){
            i++;
            $('#res').html( $('#res').html() +  i + ': ' + ($(this).val()) + '<br />' );

        });

    })
</script>
```

**Comment by Patricia-Duarte** [comment]
I'm sorry, I can no longer reproduce the error, it was probably an error in my code and now it's solved somehow. Anyway, thank you for your attention, thank's.

**Comment by FRS4002** [comment]
Hello, where is the cdn of this plugin? How can I add this plugin as cdn?
