### ISSUE TITLE
How can i detect when the delete key is pressed

### ISSUE THREAD

**Issue by mahoor-bhr** [ukalpa/inputpicker#10]
Hi @ukalpa 

Is there anyway to detect **when the** **'Delete' key is pressed** ?
For example i have a province list  that implemented by inputpicker,when it's value changed i load related cities in a dropdown ,and some info in a table.
I wanna detect when selected province is deleted and the inputpicker have an  empty value? so delete all things that relates to it.
inputpicker has  a 'change' event.but it's  not works when delete is pressed and inputpicker value is empty.

And another thing is that , how can i **highlight the filter text** ?
I wanna highlight the text that user typed  and it found in the data.

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
1. I have fixed the issue of not triggering the Change event when pressing Tab to set an empty value. Can you please try again?

2. To highlight the filter text, you can add the following section code in your program:
<style>
.inputpicker-input:focus{
    background-color: #f3f3f3;
}
</style>

**Comment by ukalpa** [comment]
Hi @mahoor-bhr, 
Can you please give me related source code if possible? So I can do the further investigation. And about the “highlight” feature, I would add it in the next few days.

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
I have added the Highlight option into the library, please use the following code to open/close highlight feature, you also can edit the highlight background colour in the inputpicker.css

`highlightResult : true`

**Comment by mahoor-bhr** [comment]
Hi @ukalpa 

Thank you for the highlight option.

and my  '.change' action when it's value is empty my code is as below 

`                $('#representorSellText').inputpicker({
                    //url: '../jsonFiles/business.json',
                    url: './serv/business/GetBusinesslist',
                    urlParam: data2,
                    fields: [
                        //{ name: 'businessId', text: ln.lb().Id },
                        { name: 'businessCode', text: ln.lb().code },
                        { name: 'businessName', text: ln.lb().name },
                        { name: 'businessCategoryName', text: ln.lb().businessCategoryName },
                        { name: 'businessCategoryCode', text: ln.lb().businessCategory },
                        { name: 'mobile', text: ln.lb().mobile },
                        { name: 'phoneNo', text: ln.lb().phone },
                        { name: 'fax', text: ln.lb().fax },
                    ],
                    autoOpen: true,
                    headShow: true,
                    fieldText: 'businessName',
                    fieldValue: 'businessId',
                    filterOpen: true,
                    pagination: true,
                    pageMode: '',
                    pageField: 'p',
                    pageLimitField: 'per_page',
                    limit: 10,
                    pageCurrent: 1,

                }).change(function (input) {
                    console.log('input ', input)
                    if (input == '') {
                        businessModel().RepresentorID(0);
                        clearInfo();
                    }
                    else {
                        var busiId = $('#representorSellText').val();
                        businessModel().RepresentorID(busiId);
                    }
                });`

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
You can not use the "input" parameter straight away in the "change" function, you should use $(this).val() to replace it:

`change(function () {
     var input = $(this).val();
                    console.log('input ', input)
                    if (input == '') {
                        businessModel().RepresentorID(0);
                        clearInfo();
                    }
                    else {
                        var busiId = $('#representorSellText').val();
                        businessModel().RepresentorID(busiId);
                    }
                });`

**Comment by mahoor-bhr** [comment]
Hi @ukalpa 

I changed my code to `var input = $(this).val();` but nothing happend for me.I couldn't get empty value in '.change' event

```
.change(function (input) {
                    var input = $(this).val();
                    console.log('inputtt ', input)
                    if (input == '') {
                        busCategoryFilter(0);
                        console.log('input ', input)

                    }
                    else {
                        var busiCatId = $('#busCategoriesfilterText').val();
                        busCategoryFilter(busiCatId);
                    }
                });
```

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
The change action is not raised when pressing 'delete' or 'backSpace', it is triggered when the input loses focus point such as user presses 'tab'.

Further explanation: when you press 'delete' or 'backSpace', it just changes the content of keyword and it does not mean the input value has been changed, so the change would not be changed at this stage until you press 'tab' or click the selected option. I hope you can understand what I mean...

**Comment by mahoor-bhr** [comment]
Hi @ukalpa 

i got it.Thanks for reply.

**Comment by ukalpa** [comment]
Cheers!

**Comment by ukalpa** [comment]
Cheers!
