### ISSUE TITLE
Inputpicker is not responsive?

### ISSUE THREAD

**Issue by duckzringz** [ukalpa/inputpicker#11]
Hello, i try to implement inputpicker to bootstrap 4 column container, but it lost responsiveness behavior by bootstrap.
I also tried to use width : '100%', which doc said will be "equal with input", still no responsive.

How can i resolve this? Thanks

**Comment by ukalpa** [comment]
Hi @duckzringz ,
Can you please give me more details about your issue such as a screenshot or source code? So I can do the further investigation. Thanks.

**Comment by duckzringz** [comment]
Hi @ukalpa ,
Here's sample of my code:
```
<div class="container">
        <div class="form-group row">
            <label for="type" class="col-4 col-form-label">Type</label>
            <div class="col-8">
                <input id="type" class="form-control" name="type" value="" />
            </div>
        </div>

        <div class="form-group row">
            <label for="name" class="col-4 col-form-label">Name</label>
            <div class="col-8">
                <input id="name" class="form-control" name="name" value="" type="text">
            </div>
        </div>
</div>

  
    <script>
        $(document).ready(function () {
            var url = '/my_json_url';
            $('#mytype').inputpicker({
                width: '100%',
                height: 300,
                headShow: true,
                url: url,
                fields: [
                    {name: 'field1', text: 'Field 1 Header'},
                    {name: 'field2', text: 'Field 2 Header'}
                ],
                fieldText: 'field1',
                fieldValue: 'field2',
                autoOpen: true
            });
        });
    </script>
```

This is normal browser display. It is correct, displayed as "col-8" class
![ss1](https://user-images.githubusercontent.com/14304315/33815233-60f46ba6-de62-11e7-8ea9-f61e8ab0a1c9.jpg)

But for responsive design (also for mobile devices), it's not automatically responsive
![ss2](https://user-images.githubusercontent.com/14304315/33815235-662322b6-de62-11e7-82a7-49d198d538fd.jpg)

And for "landscape" switch, not automatically responsive
![ss3](https://user-images.githubusercontent.com/14304315/33815237-69c774c6-de62-11e7-8a16-b8e9210e3644.jpg)

I think the problem is page "refresh". It will correctly responsive if the page refreshed.
But for mobile devices, it should be automatically "switched" for portrait/landscape mode, without refreshing the page.
(Take screenshot 3 above, regular textbox is adjusted automatically according to device width, without page refresh).

So if there any workaround, it would be great, Thanks

**Comment by ukalpa** [comment]
Hi @duckzringz ,
Thank you very much for your suggestion, I have added the responsive to the inputpicker, please update to the latest version and check again.

**Comment by duckzringz** [comment]
Hello @ukalpa ,
This is just awesome!!
It works, even though sometimes it doesn't on mobile upon switching portrait to landscape (vice versa), but i think it only occurs 2 out of 10 tries.
It's fine i think, thank you so much
