### ISSUE TITLE
how to null value

### ISSUE THREAD

**Issue by ummar091** [ukalpa/inputpicker#12]
Hello,
 1. how to set null value **`original.val()`** when fieldText not equal **input.val()**,
2. when dynamically append some input box, display _getWrappedList().show() overlapping input.val() element

**Comment by ukalpa** [comment]
Hi @ummar091 ,
1. Sorry I do not understand what means of "set null value original.val() when fieldText not equal input.val(),", can you please give me more details?
2. Usually you should not use _getWrappedList().Show straightaway.  What details of the action would you like to do in case?

**Comment by ummar091** [comment]
when i Trigger change 
$(function () {
        $('#pur-product').inputpicker({
		    url: './table_url&token=token',
		    fields: [
		        {name:'name',text:'Name'},		       
		        {name:'hsc',text:'Code'}
		    ],
		    fieldText:'name',
		    fieldValue:'Id',		    
		    tabToSelect: true
        }).blur(function (input) {
    		var data = $('#pur-product').inputpicker('element');
    		if ( $('#inputpicker-2').val() != data.name) { 
                       $('#pur-product').val('');
                }
       });
    });

**Comment by ukalpa** [comment]
Hi @ummar091 ,
You should add "trigger('change')" after setting value to activate the change action, please try:
`
$('#pur-product').val('').trigger('change');
`

**Comment by ukalpa** [comment]
Hi @ummar091 ,
Sorry that I am still not clear about your requirement based on your code snippet, do you mean?

There are three input boxes "input1", "input2" and "input3", set "input3" as "input1" when "input1" is not empty, otherwise set "input3" as "input2"

If yes, what issue do you encounter?

**Comment by ummar091** [comment]
Hello Dear,
i am sorry for my English.
i want to use normal inputbox, when required choose value from list.

**Comment by ukalpa** [comment]
Hi @ummar091 
Thanks for the suggestion. Sorry about my poor english, now I am clear your requirement, I would try to add the feature of "select or enter new" later.

**Comment by ummar091** [comment]
Thanks for your supports.

this time here night 1:45pm now i am going to sleep.

**Comment by ukalpa** [comment]
Hi @ummar091 ,

I have added the parameter "creatable" and you can set it as true to accept the input value.
`
{ creatable: true }`

**Comment by ummar091** [comment]
Hello Friend,
i do explain with you my problem.
```javascript
<input class="form-control" id="test" />
<script>
$('#test').inputpicker({
    data:[
        {value:"1",text:"Text 1", description: "This is the description of the text 1."},
        {value:"2",text:"Text 2", description: "This is the description of the text 2."},
        {value:"3",text:"Text 3", description: "This is the description of the text 3."}
    ],
    fields:[
        {name:'value',text:'Id'},
        {name:'text',text:'Title'},
        {name:'description',text:'Description'}
    ],
    fieldText : 'text',
    fieldValue: 'value',
    headShow: true,
    filterOpen: true,
    autoOpen: true,
    width: 'auto',
    urlDelay: 1,
    tabToSelect: true,
    creatable: true   
    }).blur(function (input) {
    	var data = $('#test').inputpicker('element');    		
	if ( $('#test').val() != 0 || $('#test').val() == data.value) { 
		alert('This is not empty'); 
	} else{
		alert('This is empty'); 
       }
    });
</script>
```
when i type `Text 1` that mean my `value` is set `1` this is my 1st option is `success` but my, 
2nd option is, when i type `Text 4` my `value` is set `0` how to do this.
Thanks for your supports.

**Comment by ukalpa** [comment]
Hi @ummar091 ,
I got your idea, I am thinking and will get back to you if have any update.

**Comment by ukalpa** [comment]
Hi @ummar091 ,
Following your requirement, I have added the 'selectMode' option for the plugin, you can set it as 'empty', so the input would be empty when the keyword does not match any option. Please update the source code of the plugin to the latest version and try again.

         selectMode : 'empty',

Reference: http://www.inputpicker.com/www/doc.php#options-basic (The 'selectMode' option)

**Comment by ummar091** [comment]
Hello Friend,
you are great, many thanks for about this.

**Thanks for your support.**

**Comment by ummar091** [comment]
Hello Friend,
you are great, many thanks for about this.

**Thanks for your support.**
