### ISSUE TITLE
当inputpicker再一个弹出窗体内时，如果窗口移动位置

### ISSUE THREAD

**Issue by neozhu** [ukalpa/inputpicker#15]
当inputpicker再一个弹出窗体内时，如果窗口移动位置，这时，inputpicker-wrapped-list 还是会再原始位置出现，这个问题不知道是否可以修正

**Comment by ukalpa** [comment]
Hi @neozhu ,
你能给一个例子么？我测试移动窗口inputpicker下拉会保持在新位置。

**Comment by neozhu** [comment]
https://jsfiddle.net/new163/aLbb9eso/3/
这是我简单写了一个例子，你看一下

**Comment by neozhu** [comment]
能不能从结构上修改一下呢。把 div#inputpicker-wrapped-list 包含在 div.inputpicker-div 里面。这样就可以很好的解决这种移动的问题了。

**Comment by ukalpa** [comment]
我记得外面还有一个wrapped-list外面还有一个div包着，你需要用的话可以调用那个div？这个移动我认为真的不常用，你确定你很需要用到么？很需要的话回头我回头加一下
