### ISSUE TITLE
Issue in Filter and Auto selection

### ISSUE THREAD

**Issue by gajakosh5** [ukalpa/inputpicker#18]
in Dropdown filter data an selection field not working properly

**Comment by ukalpa** [comment]
Can you please provide more details about the issue? It would be better if you could give me the example code, descriptions or screenshots. Thanks.

**Comment by gajakosh5** [comment]
in ajax mode pagination and filter not working as well as filter not working smoothly please check more time getting.

**Comment by ukalpa** [comment]
Hi @gajakosh5 ,

I still do not understand what your means about "then not shown the auto select fields", can you please explain more?

And ajax you need to filter in the backend through the param "q" as following:
![image](https://user-images.githubusercontent.com/4927815/39692872-4bbdd39c-5236-11e8-9269-34589d246dcc.png)
