### ISSUE TITLE
Get all content from the selected line

### ISSUE THREAD

**Issue by siltec** [ukalpa/inputpicker#2]
Hi, I have two questions.
1 - How can I get all content from the selected line?
2 - It is possible to add a hidden item in the field array, example
       Fields: [
         {Name: 'value', text: 'Id'},
         {Name: 'text', text: 'Title'},
         {Name: 'description', text: 'Description'},
         {Name: 'CompanyID', text: '', visible: false}

Thank you very much

**Comment by ukalpa** [comment]
Hi Siltec,

1. Can you please give me more details what all content mean? An example would be great.
2. The option "Fields" is for the fields which would be shown in the drop down, if you do not want the column to show, you do not depict it in the "Fields", please see the following example code, the "description" column is not shown.

     $('#test').inputpicker({
    data:[
        {value:"1",text:"Text 1", description: "This is the description of the text 1."},
        {value:"2",text:"Text 2", description: "This is the description of the text 2."},
        {value:"3",text:"Text 3", description: "This is the description of the text 3."}
    ],
    fields:[
        {name:'value',text:'Id'},
        {name:'text',text:'Title'}
    ]});

**Comment by ukalpa** [comment]
Hi @siltec
About your first question, please use the following code to get all content of the selected option.
var selected_row = $('#id').inputpicker('element');

**Comment by TehFox** [comment]
Hey there having the same issue, im trying to get all the content of the selected option.

tried using:
> var selected_row = $('#id').inputpicker('element');

it in fact showed me on console the values, but i cannot access them and use them.

**Comment by ukalpa** [comment]
Hi @TehFox ,
Sorry that I do not understand what your means. Can you give me the details how you cannot access and use them?
