### ISSUE TITLE
Field not responsive, only arrow is

### ISSUE THREAD

**Issue by perryraskin** [ukalpa/inputpicker#21]
Any idea why this would happen? If you notice, the down arrow is all the way on the right, but the field does not stretch to there. If I make "responsive" to "false", it cuts off the dropdown. TIA

<img width="1056" alt="screenshot 2018-04-29 01 44 02" src="https://user-images.githubusercontent.com/17967465/39403655-e73a0c30-4b4e-11e8-9e29-a1e6c2c261dc.png">

Here is my code:

```
$('#select_litters_dd').inputpicker({
  data: json,
  fields:[
    {name:'cagecard',text:'Cage Card'},
    {name:'dob',text:'Date of Birth'},
    {name:'wean_date',text:'Wean Date'},
    {name:'litter_died_date',text:'Litter Died Date'}
  ],
  headShow: true,
  fieldText : 'cagecard',
  fieldValue: 'cagecard',
  responsive: true,
  autoOpen: false,
});
```

```
<input class="form-control" id="select_litters_dd" value="Select Litter">
```

**Comment by ukalpa** [comment]
Hi @perryraskin ,
Thank you very much for the feedback. I have reproduced the issue on my env and would solve it asap.

**Comment by perryraskin** [comment]
Thanks! I personally solved it by simply giving it a width of 230%, which is good enough for what I need it for. But a responsive option would definitely be nice!
