### ISSUE TITLE
Disable this control ?

### ISSUE THREAD

**Issue by eramos23** [ukalpa/inputpicker#23]
how do i disable this control ?
When i set disabled prop, onli disabled input, but the click event is not disabled and show me tha options
![2018-05-23_15-41-27](https://user-images.githubusercontent.com/15219079/40450177-7aac618e-5ea0-11e8-9ee7-bf8ae92ce88d.png)

**Comment by ukalpa** [comment]
Hi @eramos23 ,

Thank you very much for the feedback. I have added the 'disabled' check to the plugin. Can you please update the plugin to the latest version and use the following code to set the disabled status and try again?

Set the input enable/disable:
        $("#test").prop('disabled', true);

Monitor the enable/disable event if necessary:
        $("#test").on('disable.inputpicker', function(){
            dd('disabled set: ' + $(this).prop('disabled'));
        });
