### ISSUE TITLE
Form Reset

### ISSUE THREAD

**Issue by gridr-ch** [ukalpa/inputpicker#24]
Hi, 

I am using the inputpicker with MVC5 views. 
When the form is reset with a html reset button (button type="reset"), the raw value is used again (i.e. the ID) instead of the display value. The same happens if the form had a validation error.

How can I make sure the dropdown does not disappear after a reset?

Regards,
Marcel

**Comment by ukalpa** [comment]
Hi @gridr-ch,
I would suggest you call inputpicker() again for input in the form event "reset" as follows:

        ... inputpicker()...
        
        $("form").bind("reset", function() {
            setTimeout(function() {
                $("#test").inputpicker({
                    debug: true,
                    data: [{value: "test1", segColuna: "segColuna1", terColuna: "terColuna1"},
                        {value: "test2", segColuna: "segColuna2", terColuna: "terColuna2"},
                        {value: "test3", segColuna: "segColuna3", terColuna: "terColuna3"}],
                    fields: [
                        {name: 'value', text: "value"},
                        {name: 'segColuna', text: "segColuna"},
                        {name: 'terColuna', text: "terColuna"}
                    ],
                    filterOpen: true,
                    selectMode: 'active',
                    autoOpen: true,
                    headShow: true,
                    fieldText: 'segColuna',
                    fieldValue: 'value',
                });
            }, 1);
        });
