### ISSUE TITLE
filter doesn't work if i using 'url' parameter

### ISSUE THREAD

**Issue by gaankdoank** [ukalpa/inputpicker#25]
Hi ukalpa,

you're the amazing creator. I'm very like this plugin because it's easy to use for beginner like me.
But, i've found the problem with filter feature. If i using 'data' parameter for data source, filter is running well. But if i using 'url', filter doesn't work properly. 

=
This is screenshot that i capture about the error (using 'url' parameter). 
![screenshot from 2018-07-04 15-45-22](https://user-images.githubusercontent.com/40822775/42267071-42f12da6-7fa2-11e8-8e61-22136fec0c63.png)
=
=
And this is screenshot that running well (using 'data' parameter).
![screenshot from 2018-07-04 15-46-11](https://user-images.githubusercontent.com/40822775/42267140-767caca4-7fa2-11e8-82af-559be6481f16.png)
![screenshot from 2018-07-04 15-46-21](https://user-images.githubusercontent.com/40822775/42267143-79b3bef8-7fa2-11e8-84be-788aefc13c5f.png)
=

**Comment by ukalpa** [comment]
Hi @gaankdoank ,

Thank you very much for the feedback. For the remote url, you need to handle the filter on the remote server by yourself. For example: the plugin will send request as follows when you input keyword, your remote script can get the value of the parameter "q", then, add the filter for the result. 

example-json.php?**q=abc**&limit=5&fieldValue=id&fieldText=name&value=&p=1&per_page=5

I hope the solution can solve your issue.

**Comment by gaankdoank** [comment]
Hi @ukalpa ,

I've been modified my output data, and filter running well. But, if i enable 'multiple' parameter, it just 1 data selected. If second data will select, it back to just 1. 

![screenshot from 2018-07-05 12-09-52](https://user-images.githubusercontent.com/40822775/42303700-ae2293bc-804c-11e8-8772-c4a6b469ec70.png)



![screenshot from 2018-07-05 12-10-17](https://user-images.githubusercontent.com/40822775/42303705-b3e4649c-804c-11e8-8c1d-d11524b966ca.png)



![screenshot from 2018-07-05 12-10-40](https://user-images.githubusercontent.com/40822775/42303710-b7b73b6c-804c-11e8-87fe-65420cfd1c60.png)

**Comment by ukalpa** [comment]
Hi @gaankdoank 
For multi-selections, I would suggest you do not use the filter feature on the remote. The system does not know which keyword should be posted to the remote server.
