### ISSUE TITLE
Searching not working after selecting

### ISSUE THREAD

**Issue by hbhardikpatel** [ukalpa/inputpicker#26]
Hello Sir,

I am following below steps.

1 ) I have search "India" and then press down arrow key and selected "Ireland".
2 ) After selecting "Ireland" click outside of dropdown.
3 ) I am second time searching india but not getting result with india selected. ( i have debug your js i think there is a problem in   " if (tr_active.position().top < tr_active.outerHeight()) " in this condition ) @ukalpa 
![1](https://user-images.githubusercontent.com/42140020/43712432-c9f8f03a-9993-11e8-8815-2f3dd0f0507f.png)
![2](https://user-images.githubusercontent.com/42140020/43712445-d5d9b27c-9993-11e8-8177-484f60d4fa74.png)
![3](https://user-images.githubusercontent.com/42140020/43712454-d95a80ac-9993-11e8-9621-7134c94e9c5d.png)

**Comment by ukalpa** [comment]
Hi @hbhardikpatel ,

Can you please show me the source code? I can reproduce the issue you described.
