### ISSUE TITLE
How can i add new value in array

### ISSUE THREAD

**Issue by hbhardikpatel** [ukalpa/inputpicker#27]
Hello Sir,

I want to add new element in array or in grid, it is possible ?

Thanks,
Hardik Patel

**Comment by ukalpa** [comment]
Hi @hbhardikpatel ,

You can recall ".inputpicker" with new Array with the new element to reset options, cheers.

**Comment by hbhardikpatel** [comment]
@ukalpa thank you sir, it's working now.
