### ISSUE TITLE
how I get all value of selected row

### ISSUE THREAD

**Issue by eramos23** [ukalpa/inputpicker#3]

**Comment by ukalpa** [comment]
Hi @eramos23 ,
Good suggestion. I have added a function to get the selected object in the library, please update "jquery.inputpicker.js" to the latest version, then use the following method to get all value of selected row:

`$('#id').inputpicker('element');`

**Comment by eramos23** [comment]
thank you very much,
Greetings from Perú 👍 :D

**Comment by ukalpa** [comment]
Cheers.

**Comment by ummar091** [comment]
Hi, 
   this is a very nice tools and work perfectly, but my some issued follows:
1. can option Fixed table header true/false.
2. resize table width automatically.
3. how to get any one fields  value example..
##<script>
	$(function () {
        $('#auto-product').inputpicker({
		    url: 'index.php?route=ajaxMultiTable',
		    fields:['Name', 'Brand', 'Models', 'HSC', 'Stock', 'Tax', 'Price', 'MRP'],	    
		    fieldText:'Name',
		    fieldValue:'Id',
		    headShow: true,
		    filterOpen: true,
		    autoOpen: true,
		    width: '850px'
        });
        $('#auto-product').change(function(){
            var selected_row  = $('#auto-product').inputpicker('element');
            console.log( selected_row['Price'] );
           $('#ans-product').val(selected_row['Price']);
        });
    })  
</script>

## **another example like**

$('#tab-pro input[name=\'cproduct\']').autocomplete({
	'source': function(request, response) {
		$.ajax({
			url: 'index.php?autocomplete&filter_name=' +  encodeURIComponent(request),
			dataType: 'json',
			success: function(json) {
				response($.map(json, function(item) {
					return {
						label: item['name'],
						value: item['product_id'],
						quantity: item['quantity']
					}
				}));
			}
		});
	},
	'select': function(item) {
		$('#tab-pro input[name=\'cproduct\']').val(item['label']);
		$('#tab-pro input[name=\'cproduct_id\']').val(item['value']);
		$('#tab-pro input[name=\'qty\']').val(item['quantity']);
	}
});`

thank you!
