### ISSUE TITLE
How to Set Selected Value to inputpicker in Textbox

### ISSUE THREAD

**Issue by bobby5300** [ukalpa/inputpicker#31]
How to Set Selected Value to inputpicker in Textbox Dynamically 

I am trying with below statement, but nothing works

$("#test").val("1");

<input class="form-control" id="test"/>

$('#test').inputpicker({
    data:[
        {value:"1",text:"Text 1", description: "This is the description of the text 1."},
        {value:"2",text:"Text 2", description: "This is the description of the text 2."},
        {value:"3",text:"Text 3", description: "This is the description of the text 3."}
    ],
    fields:['value','text','description'],
    fieldText : 'text',
    multiple: true,
    headShow: true,
    filterOpen: true,
    autoOpen: true
});

**Comment by ukalpa** [comment]
Hi @bobby5300 ,

You need to put $("#test").val("1") to the behind of inputpicker()....
