### ISSUE TITLE
Arrow down not a function..

### ISSUE THREAD

**Issue by Designburo** [ukalpa/inputpicker#33]
This is my setup ..  Typing and searching works. But clicking on the button-down arrow gives me :

> TypeError: $(...).parent(...).find(...).inputpicker is not a function

`function doTokenSetup(){ 
$('#tokener2').inputpicker({ 
placeholder: 'Choose..',
url: 'example-districts.json',
fields: ['id', 'name', 'hasc'] ,
fieldText: 'name',
fieldValue: 'id',
filterOpen: true,
selectMode: 'creatable',
multiple: true,
headShow: true
});
}`

**Comment by Designburo** [comment]
Also .. when using the above setup it looks like some CSS styling is missing. e.g. the border around the input text field is gone. So its hard to see where you can start typing.

**Comment by ukalpa** [comment]
Hi @Designburo ,
I am unable to reproduce the issue according to the desc. Can you please provide more details about the issue? It would be great if you could upload your source code to https://jsfiddle.net/ . Thanks a lot.
