### ISSUE TITLE
Set manually a value

### ISSUE THREAD

**Issue by mctdi** [ukalpa/inputpicker#38]
I use input picker in a form.

$('#samplingsFactories').inputpicker({
                        data:[                
 { "id": "13", "Machine": "946 - REK1" , "Description": "Rekers", "Usines": "Mis" } ,
 { "id": "8", "Machine": "922 - BES1" , "Description": "Besser", "Usines": "Laval" } 
                        ],
                        fields:['Machine','Description','Usines'],
                        fieldText : 'Machine',
                        fieldValue : 'id',
                        headShow: true,
                        filterOpen: false,
                        autoOpen: true
                    });

I get value selected in the input picker and put it in a variable.

var inputSelected = $('#samplingsFactories').val();
I do a reset of a form.

I set again the value.
$('#samplingsFactories').val(inputSelected);

At the screen input picker don't display the selected value.

Is there a way to get it

**Comment by ukalpa** [comment]
Hi @mctdi ,

Can you please try to use $('#samplingsFactories').inputpicker('val', inputSelected) to update the value?
In my memory, if you use val() straightaway, you also need to trigger the change function.
