### ISSUE TITLE
Can I hide the fieldValue column

### ISSUE THREAD

**Issue by Bugswald** [ukalpa/inputpicker#4]
I am wondering if there is a way to hide the column which has been chosen as the fieldValue.

For example, I have set the fieldValue to my "Id" column; however, since that ID number does not mean anything to my users, I would prefer to hide it so that my users do not see it as a column in the dropdown listing.

**Comment by ukalpa** [comment]
Hi @Bugswald ,
Please use the parameter "fields" to set which fields you want to show in the dropdown listing. You can remove "Id" from it and "Id" will not be shown in the list.

```
fields: ['Name', 'Description'],
fieldValue: 'Id',
```

**Comment by Bugswald** [comment]
Thank you for your VERY quick response!  Your suggestion allows me to do what I needed.

**Comment by ukalpa** [comment]
Cheers!
