### ISSUE TITLE
Ajax before every open

### ISSUE THREAD

**Issue by typer139** [ukalpa/inputpicker#40]
Would it be possible to extended the capability to make the data ajax call before every open?.. I'm trying to keep my data fresh... maybe a beforeOpen function.

**Comment by ukalpa** [comment]
Hi @typer139 ,

When you input the keyword, the plugin will send Ajax request to the remote url, so there is no requirement to fresh when opening the selection.

**Comment by typer139** [comment]
Thanks for the reply.  True.. it does when I type.. but when I have autoOpen on, and click into the field, the ajax doesn't execute.  Is there a workaround to make that magic work?

**Comment by ukalpa** [comment]
Hi @typer139

What do you mean the Ajax does not execute? Can you please show me your code and which browser you are using?

**Comment by typer139** [comment]
Absolutely.. I'm currently not using any pagination.. hence the commenting out of those option lines.. 

$('#resource').inputpicker({
	url: window.location.href+'&getrecs=true&type=P',
	fields:['Name','Qty','Available','Cost','Unit','Supplier'],
	autoOpen: true,
	headShow: true,
	fieldText : 'Name',
	fieldValue: 'id',
	filterOpen: true
//	pagination: true,
//	pageMode: '',
//	pageField: 'p',
//	pageLimitField: 'per_page',
//	pageCurrent: 1,
})

**Comment by ukalpa** [comment]
Hi @typer139 ,

Not sure why it does not work properly in your code, or can you please try the code in the document as below?

![2019-03-11 08_41_13-Inputpicker - A jQuery plugin of supporting multiple columns by Ukalpa(ukalpa@gm](https://user-images.githubusercontent.com/4927815/54090515-d6125280-43d9-11e9-9bfe-24cffe3ae14a.png)
