### ISSUE TITLE
Pagination is not working

### ISSUE THREAD

**Issue by OsamaMunawar** [ukalpa/inputpicker#41]
I don't why but pagination is not working. I have used your example-regions.json to bind data with input picker. Input picker is showing the all 17 records on page 1. Pagination is working. Please solve my problem I will be very thankful to you.

$('#test').inputpicker({
               
                url: './example-regions.json',
                fields: ['id', 'name', 'hasc'],
                fieldText: 'name',
                fieldValue: 'id',
                pagination: true,
                pageMode: '',
                pageField: 'p',
                pageLimitField: 'per_page',
                limit: 5,
                pageCurrent: 1,
            });

I have also follow below link 
http://www.wangshui.com/www/  (JSON - Remote Search with Pagination)

I have attached a photo also. I am working on asp.net web forms

![Capture](https://user-images.githubusercontent.com/48879206/55110622-3f90a180-50fa-11e9-86be-dbf17268ce98.JPG)

**Comment by ukalpa** [comment]
Hi @OsamaMunawar ,
For the pagination from the remote URL, please ignore the parameter "limit" and use the following parameters posting to the remote server to limit the result data:

per_page=5 // limit 5 records per page
p = 1 // the current page

Please check the below URL as the reference as the structure of the returned data: 
http://inputpicker.com/www/example-json.php?q=&limit=1&fieldValue=id&fieldText=name&value=&p=1&per_page=5

**Comment by OsamaMunawar** [comment]
Sir sorry but please tell how can I set or restrict per_page=5 and p=1 in javascript

**Comment by ukalpa** [comment]
Hi @OsamaMunawar ,
Sorry that so far the plugin does not support paginating data from the static JSON file like your scenario. If you want the pagination feature you have to handle data in the dynamic script on the server.

**Comment by OsamaMunawar** [comment]
First I try it from my server. Input picker "url" property is not hitting my server method that will return the data from my server. I think that I can make the call wrong to server method and then cross verify by making ajax call to that server that ant it return data from my server method. But in ur case it is not working when I give server's method.

   $('#test').inputpicker({
                url: 'PDCAddUpdate.aspx/GetCustomers',
                //url: './example-regions.json',
             
                    fields: ['value', 'text', 'description'],
                    fieldText: 'text',
                    fieldValue: 'value',
                    pagination: true,
                    pageMode: '',
                    pageField: 'p',
                    pageLimitField: 'per_page',
                    limit:1,
                    pageCurrent: 1,
});

This is not getting the data. PDCAddUpdate is the page and getcustomers is the webmethod

**Comment by ukalpa** [comment]
Hi @OsamaMunawar ,
Sorry that I have no idea the reason for your issue, can you please post your server script source code and the error which you get from the console of the web browser?

**Comment by OsamaMunawar** [comment]
The problem is it is not redirecting to my Method GetCustomers when I give url property like 
url: 'PDCAddUpdate.aspx\GetCustomers '
but When I give url property like this
url: 'PDCAddUpdate.aspx'
os it my page load event of page PDCAddUpdate executes only and in web forms page load event cannot return any data so this input picket cannot be bind. Please check why this url property it not executing why I give method name also

**Comment by OsamaMunawar** [comment]
Hi ukalpa
Now I have successfully bind input picker from remote url. we are getting this data from remote URL

  $('#test').inputpicker({
                url: 'http://localhost:30819/UI/Pages/Welcome/Popupdata.aspx',
               
                fields: ['id', 'region_id', 'name', 'hasc', 'region_name'],
                fieldText: 'name',
                fieldValue: 'id',
                pagination: true,
                pageMode: '',
                pageField: 'p',
                pageLimitField: 'per_page',
                limit:1,
                pageCurrent: 1,
            });

In this scenario pagination is not working. I have also attached a snapshot of network request per_page =1. If I have to change per page so please tell me that how can I change.

![PaginationIssue](https://user-images.githubusercontent.com/48879206/55147418-29212f00-5168-11e9-9a9a-e4fbb36f4bb1.JPG)

**Comment by ukalpa** [comment]
Hi @OsamaMunawar ,
You need to handle the pagination logic in the script http://localhost:30819/UI/Pages/Welcome/Popupdata.aspx, as we can see, although you set per_page=1, your script still outputs all data in the response, this is why it shows all data in the front end.

**Comment by OsamaMunawar** [comment]
Thanks ukalpa for support. It is just a request to provide pagination option mai other examples also.
