### ISSUE TITLE
Issues In Bootstrap Modal

### ISSUE THREAD

**Issue by KirenJames7** [ukalpa/inputpicker#43]
Hi
Is there a fix for this? I am also experiencing a bug when the element is on a modal. No issue with the UI. But the search input doesn't accept the keyboard input. Even after the value is selected cant you back space or delete to remove it. Arrow key navigation also differs.

[Screencast 2019-04-18 10:18:30.zip](https://github.com/ukalpa/inputpicker/files/3092779/Screencast.2019-04-18.10.18.30.zip)

_Originally posted by @KirenJames7 in https://github.com/ukalpa/inputpicker/issues/39#issuecomment-484354745_

**Comment by ukalpa** [comment]
Hi @KirenJames7 ,

Can you please provide the source code for me to investigate? I am unable to figure out the reason through the video...

**Comment by KirenJames7** [comment]
Hi
I am unable to share the source code that I am working on currently. It will take sometime for me to share a replicated source. Will share ASAP.

**Comment by KirenJames7** [comment]
Hi

So I managed to figure out a major bug in this plugin. This plugin cannot be used within a form when using bootstrap. As soon as the form tags are used, issues I have mentioned above arises. Additionally the element on change method fires an infinite loop that does not exit even after the event is fired. I also manage to figure out that this has nothing to do with modals as even an on page form causes this issue.

[inputpicker-master without form.zip](https://github.com/ukalpa/inputpicker/files/3123519/inputpicker-master.without.form.zip)
[inputpicker-master with form.zip](https://github.com/ukalpa/inputpicker/files/3123520/inputpicker-master.with.form.zip)

**Comment by KirenJames7** [comment]
Issue not with Modal. Issue arises when used with form element. without form it works fine.
