### ISSUE TITLE
Anchor tag inside into td 

### ISSUE THREAD

**Issue by AhmedKDS** [ukalpa/inputpicker#51]
Actually i want to bind the data through inputpicker with giving edit functionality.
When i tried to bind anchor tag inside into fireld[ text:<a></a>] there is showing into <th> not <td>.

**Comment by ukalpa** [comment]
Could you please post your souce code at here for the further investigation?

**Comment by AhmedKDS** [comment]
$('#id').inputpicker({
                        data: json,
                        fields: [
                      { name: 'CaseID', text: 'Case ID' },
                            { name: 'CaseName', text: 'Case Name' },
                            { name: 'PrimaryPolicyNumber', text: 'Primary Policy #' },
                            { name: 'PrimaryCompanyName', text: 'Primary Insurance Name', 'style': 'width: 25%;' },
                            { name: 'SecondaryPolicyName', text: 'Secondary Policy #' },
                            { name: 'SecondaryCompanyName', text: 'Secondary Insurance Name' },
							 { name: 'Edit', text: "<a  id='anId' href='javascript:void(0)' > </a>" },
                        ],
                        headShow: true,
                        fieldText: 'CaseID',
                        fieldValue: 'CaseID'
                    });
					
![Case](https://user-images.githubusercontent.com/55793609/76418433-a15a2200-63c4-11ea-97ba-62431f88bf66.png)

**Comment by AhmedKDS** [comment]
$('#id').inputpicker({
                        data: json,
                        fields: [
                      { name: 'CaseID', text: 'Case ID' },
							 { name: 'Edit', text: "<a  id='anId' href='javascript:void(0)' > ID </a>" },
                        ],
                        headShow: true,
                        fieldText: 'CaseID',
                        fieldValue: 'CaseID'
                    });
![image](https://user-images.githubusercontent.com/55793609/76419162-ea5ea600-63c5-11ea-9fcc-a656aeb9f0ba.png)

**Comment by AhmedKDS** [comment]
![image](https://user-images.githubusercontent.com/55793609/76419240-05311a80-63c6-11ea-91e6-bec901897be0.png)


$('#id').inputpicker({
                        data: json,
                        fields: [
                      { name: 'ID', text: 'Case ID' },
							 { name: 'Edit', text: "<a  id='anId' href='javascript:void(0)' > ID </a>" },
                        ],
                        headShow: true,
                        fieldText: 'ID',
                        fieldValue: 'ID'
                    });

**Comment by AhmedKDS** [comment]
![image](https://user-images.githubusercontent.com/55793609/76420215-c7cd8c80-63c7-11ea-8ccf-18e47c0bdd71.png)


Like this Edit functionality

**Comment by ukalpa** [comment]
Sorry, I still do not understand your question..... Could you please explain more?

**Comment by AhmedKDS** [comment]
I am talking about CRUD operation like Create , Read , Update and Delete through gridview, in this there is a facility about row editing and deleting fetaures. I am giving you the reference of the website.
I think it will be helpful to you.

 Please  use this website , it will give you and idea about that 👎 https://www.aspsnippets.com/Articles/Edit-Update-and-Delete-in-ASPNet-GridView-with-AutoGenerateColumns-True-using-C-and-VBNet.aspx

http://www.dotnetfox.com/articles/how-to-add-edit-delete-update-records-in-grid-view-Asp-Net-1003.aspx

https://www.c-sharpcorner.com/UploadFile/9f0ae2/gridview-edit-delete-and-update-in-Asp-Net/

I think its helpful to you , I have already applied inputpicker in my code and already deployed the code on server and client demands the functionality of editing and deleting.

**Comment by ukalpa** [comment]
Let us back into your question, could you please explain what means of "there is showing into not ."

**Comment by AhmedKDS** [comment]
Please see the attachment of current inputpicker. I want to just give the functionality of editable
and delete the row.
When i click on edit / delete , it will hit into database and edit/ delete the row.



![image](https://user-images.githubusercontent.com/55793609/76616625-6d106e00-654a-11ea-8743-85540bc5f589.png)


![image](https://user-images.githubusercontent.com/55793609/76616785-ce384180-654a-11ea-8979-b6029e7c7353.png)

**Comment by AhmedKDS** [comment]
Anchor tag is currently showing in <th> not <td>. As i already attached the screenshot .
Please tell me when you are free.  i want to call with you on skype.
Just drop a message on this whatsapp number : +91-7011348177.

**Comment by AhmedKDS** [comment]
Hello ,
Are you working on the same?

**Comment by AhmedKDS** [comment]
Please do letme know if it is possible or not.

**Comment by ukalpa** [comment]
Hi,
I tested HTMLcode in the content and head and both of them working fine.

![image](https://user-images.githubusercontent.com/4927815/76791481-e3042600-6825-11ea-9c7f-6c65a6f2af36.png)

**Comment by AhmedKDS** [comment]
Thanks for issue my problem.
Could you please provide me the demo source code?

**Comment by ukalpa** [comment]
Here:

```
$(function () {
                            $('#test').inputpicker({
                                width:'100%',
                                data: [
                                    {id:1, name:'Auckland', 'hasc': '<a href="#" onclick="alert(\'Auckland\');event.preventDefault();event.stopPropagation()">Auckland</a>'},
                                    {id:2, name:'Wellington', 'hasc': '<a href="#" onclick="alert(\'Wellington\');event.preventDefault();event.stopPropagation()">Wellington</a>'}
                                ],
                                fields:['id','name',{name:'hasc', text: '<a id="anId" href="javascript:void(0)">HASC</a>'}],
                                fieldText:'name',
                                fieldValue:'id',
                                headShow: true,
                            });
                        });
```

**Comment by AhmedKDS** [comment]
Thanks i will apply the same.

**Comment by AhmedKDS** [comment]
Hello, 
I am binding the data dynamically inside the table from the database and you have given me static data. Please check and revert.

![image](https://user-images.githubusercontent.com/55793609/76948498-2e552c00-692d-11ea-87b6-c59ffda91dd3.png)

![2020-03-18_1521](https://user-images.githubusercontent.com/55793609/76947953-63ad4a00-692c-11ea-9d22-a5c640ca84e8.png)
![2020-03-18_1512](https://user-images.githubusercontent.com/55793609/76947959-660fa400-692c-11ea-921b-e7b694196b0f.png)

**Comment by AhmedKDS** [comment]
I don't know how many data receives from data base and according to your code , how will apply the same.i want to put edit button tag whether i receives 1 or more than one records.

**Comment by AhmedKDS** [comment]
![image](https://user-images.githubusercontent.com/55793609/76949689-f51dbb80-692e-11ea-9cfb-26922aa8740d.png)

**Comment by ukalpa** [comment]
Sorry I am unable to help you, maybe it is better that you post the question on the StackOverflow.com
