### ISSUE TITLE
inputpicker 

### ISSUE THREAD

**Issue by rusty686** [ukalpa/inputpicker#54]
Hi 
I'm trying to make the list produced by inputpicker react to the up and down arrows. 
I am displaying a list of records from a database. When I click a row in the list, I use the 'change' event to get that row's record and display the fields in some html. 
I want to get the same effect by using the up/down keys, instead of clicking.
I have tried triggering the 'change' event in response to an 'onkeyup' event, but that just gets the value of the previously clicked row.
I'm sure it can be done. I just can't get it to work. Can anybody help please.
Best regards
Russ Dear 
delivery@hambleyacht.net

**Comment by ukalpa** [comment]
Hi @rusty686 ,

I have updated the code following your requirement, please download the latest code and refer the below sample:

```
$('#test').on('change_highlight.inputpicker', function (){
    var val = $(this).inputpicker('value_highlighted');
    // console.log("Highlight row is changed'", $(this).inputpicker('data_highlighted'), val);
    $(this).val(val).trigger('change');
    // console.log("Row is changed'", $(this).inputpicker('data_highlighted'), val);
 });
```

**Comment by rusty686** [comment]
Brilliant ukalpa

 

Thank you so much for your speedy response.

 

I will try the code today and get back to you.

 

Cheers Russ

**Comment by rusty686** [comment]
Hi ukalpa
I have now implemented your new code, and it works well, thank you.
It does do a bit more than I wanted, in that it fires for each record as the mouse is moved over the list. 
Ideally I would want the selection to be made either by clicking a row, or moving over the rows with the up/down keys.
I appreciate that this may not be easily possible. Thank you for your help.
Cheers Russ

**Comment by rusty686** [comment]
Hi ukalpa 
Update
I appear to have achieved the functionality I was looking for by adding the code below to a 'window.onload' function
  $("#inputpicker-1").on("keyup",function(){
    var val = $('#test').inputpicker('value_highlighted');
    $('#test').val(val).trigger('change');
  });
Cheers Russ

**Comment by rusty686** [comment]
Hi ukalpa
Update to Update
The previous code I sent needs a mod to restrict the action to up/down arrow keys. See below.

  $("#inputpicker-1").on("keyup",function(){
    var key = event.which;
    if (key == 38 || key == 40){ // check for an up/down arrow key, if not exit
      var val = $('#test').inputpicker('value_highlighted');
      $('#test').val(val).trigger('change');
    }else{
      return false;
    }
  });

**Comment by ukalpa** [comment]
Hi @rusty686 ,

So you got the solution now?

**Comment by rusty686** [comment]
Hi ukalpa
Yes, it looks like the code I show above, put into a 'window.onload' function, works fine. Thank you for your help, and keep up the good work.
Cheers Russ

**Comment by ukalpa** [comment]
That's great, I will close the issue.
