### ISSUE TITLE
Change Font size and type of arrow icon

### ISSUE THREAD

**Issue by baxing** [ukalpa/inputpicker#55]
Hi ukalpa,

If I want to increase the font size in the table shown on the list. What can I do?
And if you want to change the icon of the arrow, how can I do it?

Thanks.

**Comment by ukalpa** [comment]
Hi,

Increase the font size in the table shown:
<style>
    .inputpicker-wrapped-list table td {
        font-size:16px; 
    }
</style>

Change the icon of the arrow:
Search “inputpicker-arrow” and change it.

Refer: https://inputpicker.com/doc.php

**Comment by baxing** [comment]
Thank you very much
