### ISSUE TITLE
Inputpicker issues on iPhone and iPad

### ISSUE THREAD

**Issue by darrelljones22** [ukalpa/inputpicker#6]
Hello, 

I have been using your jquery inputpicker, and it has really been easy to use. However, I am having some issues with script errors on iPhone and iPad displays. Is this something that you have encountered before? These are errors related to assigning values to readyonly properties.

Thanks.

Darrell Jones

**Comment by ukalpa** [comment]
Hi Darrell,
I tested it in Chrome on iPhone and it is working fine. Can you please give me more details which errors you encounter in your environment, so I could solve them for you.
