### ISSUE TITLE
Detect scroll in inputpicker plugin and load more data

### ISSUE THREAD

**Issue by mahoor-bhr** [ukalpa/inputpicker#8]
i'm working with Mvc.net & knockout.js .i use inputpicker plugin to bind my data in a select list.
data that shown in the inputpicker list is a large amount of data.so i wanna load chunk of data in scroll.

i try this code ,but it's not the solution.because i can't implement this code as a seperate function in inputpicker plugin and trigger it when it's needed.

so , how can i get data in scroll of inputpicker?

var wrapped_list = $('#inputpicker-wrapped-list');

wrapped_list.on('scroll', function (e) {

 var elem = e.currentTarget;

if (elem.scrollHeight - elem.scrollTop <= elem.clientHeight) {

loadMoreData();

            }
        }
    });

**Comment by ukalpa** [comment]
Hi Mahoor,
Thank you for the feedback. "inputpicker-wrapped-list" is for internal use in the "Inputpicker" and should not be called straight away. To solve the issue, can you please give me more details and the whole test code if possible?

**Comment by mahoor-bhr** [comment]
@ukalpa Tnx for your reply.

i wanna show all data by inputpicker but chunk by chunk.

for example my products table ,has  about 9000 records.i don't wanna load all of them in the first time.

i need something like paging,or a button in inputpicker list ,like  'load more data',
or something like an event to detect scroll and trigger an event to get rest of the data.

**Comment by ukalpa** [comment]
Hi @mahoor-bhr 
I got your ideas, I would add the pagination feature in the next few days for you and I think it is a better way to add the event to check scroll.

**Comment by mahoor-bhr** [comment]
Hi @ukalpa 
This feature will help me a lot.
So i'm waiting for this feature...   :-)

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
I have added new pagination option in the library, now you can set the relevant options per your requirements, please check the document as below and contact me if have any problem, thanks.
Example: http://www.inputpicker.com/www/#remote-pagination
Document: http://www.inputpicker.com/www/doc.php#options-pagination

**Comment by mahoor-bhr** [comment]
Good job @ukalpa 
Thanks for the pagination feature .
I add the pagination to my project.I don't know how set the records count as u set.
my records count is a field of the  json array,i mean ,it's in the jsonArray that i got from server.

```
$('#representorSellText').inputpicker({
                    url: './serv/business/GetBusinesslist?b=' + config.currentBusinessId() + '&u=' + config.currentUserId() + '&t=' + enums.Representor,
                    
                    fields: [
                        { name: 'businessId', text: ln.lb().Id },
                        { name: 'businessName', text: ln.lb().name },
                        { name: 'businessCode', text: ln.lb().code },
                        { name: 'businessCategoryName', text: ln.lb().businessCategoryName },
                        { name: 'businessCategoryCode', text: ln.lb().businessCategory },
                        { name: 'mobile', text: ln.lb().mobile },
                        { name: 'phoneNo', text: ln.lb().phone },
                        { name: 'fax', text: ln.lb().fax },
                    ],
                    autoOpen: true,
                    headShow: true,
                    fieldText: 'businessName',
                    fieldValue: 'businessId',
                    filterOpen: true,
                    pagination: true,
                    pageMode: '',
                    pageField: 'p',
                    pageLimitField: 'per_page',
                    //pageCount: 'count',  //_**you wrote that this is for system use**_
                    //pageCountField: 'count',
                    count: 'count',
                    limit: 10,
                    pageCurrent: 1,

                }).change(function (input) {
                    var busiId = $('#representorSellText').val();
                    businessModel().RepresentorID(busiId);
                });

```

**Comment by ukalpa** [comment]
Hi @mahoor-bhr ,
Please return JSON data as the following format:

```
{
     "msg" : "",
     "count" : 200,
     "data" : [
            { "businessName": "Mahoor", "id": 89540674, "businessId": 15, "businessCode": "000014",      "businessCategoryCode": "02", "businessCategoryName": "Representor", "recordCount": "3096"},
            { "businessName": "Mahoor", "id": 89540674, "businessId": 15, "businessCode": "000014",      "businessCategoryCode": "02", "businessCategoryName": "Representor", "recordCount": "3096"},
            { "businessName": "Mahoor", "id": 89540674, "businessId": 15, "businessCode": "000014",      "businessCategoryCode": "02", "businessCategoryName": "Representor", "recordCount": "3096"}
}
```

**Comment by mahoor-bhr** [comment]
Thank you @ukalpa.All of my problems solved with your descriptions and the new pagination feature.

**Comment by ukalpa** [comment]
@mahoor-bhr Cheers, I would close this issue, thanks for your suggestions and please continue to feedback  if you encounter any problems.
