### ISSUE TITLE
Can i get any one field value on change

### ISSUE THREAD

**Issue by ummar091** [ukalpa/inputpicker#9]
Hello, Dear
my console.log showing : {Id: "17", Name: "HDD", Brand: "WD", Models: "1TB DESKTOP", HASC: "84717020", …}

how to get value var rValue = $('#r-prod').inputpicker('element', 'Brand'); 
not a fieldText:'Name', or
fieldValue:'Id',  i actually get other value, please help me

**Comment by ukalpa** [comment]
Hi @ummar091 :+1: 
Thank you very much for the feedback. I have revised the 'element' function, and you can get the specific element through the following method:
`$('#r-prod').inputpicker('element', 'value', 'fieldName');`

**Comment by ummar091** [comment]
Thank you very much for best compliment.
